"""Initial schema

Revision ID: a2389e42f3b3
Revises: 
Create Date: 2026-08-10 21:19:15.591980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2389e42f3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS clothing_store')
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=30), nullable=False),
    sa.Column('branch_name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('branch_id', name=op.f('pk_branches')),
    sa.UniqueConstraint('branch_code', name=op.f('uq_branches_branch_code')),
    schema='clothing_store'
    )
    op.create_table('carts',
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cart_id', name=op.f('pk_carts')),
    schema='clothing_store'
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['clothing_store.categories.category_id'], name=op.f('fk_categories_parent_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('category_code', name=op.f('uq_categories_category_code')),
    schema='clothing_store'
    )
    op.create_table('colors',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=60), nullable=False),
    sa.Column('color_code', sa.String(length=40), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('color_id', name=op.f('pk_colors')),
    sa.UniqueConstraint('color_code', name=op.f('uq_colors_color_code')),
    schema='clothing_store'
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_code', sa.String(length=50), nullable=False),
    sa.Column('offer_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('benefit_type', sa.String(length=30), nullable=False),
    sa.Column('min_cart_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('target_branch_id', sa.Integer(), nullable=True),
    sa.Column('target_category_id', sa.Integer(), nullable=True),
    sa.Column('target_product_id', sa.Integer(), nullable=True),
    sa.Column('target_variant_id', sa.Integer(), nullable=True),
    sa.Column('target_scope', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stacking_policy', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('offer_id', name=op.f('pk_offers')),
    sa.UniqueConstraint('offer_code', name=op.f('uq_offers_offer_code')),
    schema='clothing_store'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applied_offer_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number')),
    schema='clothing_store'
    )
    op.create_table('sizes',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=20), nullable=False),
    sa.Column('size_type', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('size_id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('size_label', 'size_type', name=op.f('uq_sizes_size_label')),
    schema='clothing_store'
    )
    op.create_table('cart_items',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['clothing_store.carts.cart_id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'variant_id', 'branch_id', name=op.f('uq_cart_items_cart_id')),
    schema='clothing_store'
    )
    op.create_table('order_items',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('article_code', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['clothing_store.orders.order_id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_order_items')),
    schema='clothing_store'
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('article_code', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=160), nullable=True),
    sa.Column('fit', sa.String(length=60), nullable=True),
    sa.Column('season', sa.String(length=80), nullable=True),
    sa.Column('base_cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_status', sa.String(length=30), nullable=False),
    sa.Column('availability_scope', sa.String(length=40), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['clothing_store.categories.category_id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products')),
    sa.UniqueConstraint('article_code', name=op.f('uq_products_article_code')),
    schema='clothing_store'
    )
    op.create_index('ix_products_category_status', 'products', ['category_id', 'product_status'], unique=False, schema='clothing_store')
    op.create_table('product_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=250), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['clothing_store.colors.color_id'], name=op.f('fk_product_images_color_id_colors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['clothing_store.products.product_id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_product_images')),
    schema='clothing_store'
    )
    op.create_index('ix_product_images_primary', 'product_images', ['product_id', 'is_primary'], unique=False, schema='clothing_store')
    op.create_table('product_variants',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('barcode', sa.String(length=30), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['clothing_store.colors.color_id'], name=op.f('fk_product_variants_color_id_colors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['clothing_store.products.product_id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['clothing_store.sizes.size_id'], name=op.f('fk_product_variants_size_id_sizes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('variant_id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('barcode', name=op.f('uq_product_variants_barcode')),
    sa.UniqueConstraint('product_id', 'color_id', 'size_id', name=op.f('uq_product_variants_product_id')),
    sa.UniqueConstraint('sku', name=op.f('uq_product_variants_sku')),
    schema='clothing_store'
    )
    op.create_index('ix_variants_product_active', 'product_variants', ['product_id', 'is_active'], unique=False, schema='clothing_store')
    op.create_table('branch_inventory',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('in_transit_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('max_stock_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['clothing_store.branches.branch_id'], name=op.f('fk_branch_inventory_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['clothing_store.product_variants.variant_id'], name=op.f('fk_branch_inventory_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('pk_branch_inventory')),
    sa.UniqueConstraint('branch_id', 'variant_id', name=op.f('uq_branch_inventory_branch_id')),
    schema='clothing_store'
    )
    op.create_index('ix_inventory_variant_branch', 'branch_inventory', ['variant_id', 'branch_id'], unique=False, schema='clothing_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_variant_branch', table_name='branch_inventory', schema='clothing_store')
    op.drop_table('branch_inventory', schema='clothing_store')
    op.drop_index('ix_variants_product_active', table_name='product_variants', schema='clothing_store')
    op.drop_table('product_variants', schema='clothing_store')
    op.drop_index('ix_product_images_primary', table_name='product_images', schema='clothing_store')
    op.drop_table('product_images', schema='clothing_store')
    op.drop_index('ix_products_category_status', table_name='products', schema='clothing_store')
    op.drop_table('products', schema='clothing_store')
    op.drop_table('order_items', schema='clothing_store')
    op.drop_table('cart_items', schema='clothing_store')
    op.drop_table('sizes', schema='clothing_store')
    op.drop_table('orders', schema='clothing_store')
    op.drop_table('offers', schema='clothing_store')
    op.drop_table('colors', schema='clothing_store')
    op.drop_table('categories', schema='clothing_store')
    op.drop_table('carts', schema='clothing_store')
    op.drop_table('branches', schema='clothing_store')
    # ### end Alembic commands ###
