"""Add delivery info to orders

Revision ID: bc565804fbc9
Revises: d71903008a2c
Create Date: 2026-08-11 12:50:23.797282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc565804fbc9'
down_revision: Union[str, Sequence[str], None] = 'd71903008a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=100), nullable=True), schema='clothing_store')
    op.add_column('orders', sa.Column('phone', sa.String(length=20), nullable=True), schema='clothing_store')
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True), schema='clothing_store')
    op.add_column('orders', sa.Column('city', sa.String(length=50), nullable=True), schema='clothing_store')
    op.add_column('orders', sa.Column('delivery_notes', sa.Text(), nullable=True), schema='clothing_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_notes', schema='clothing_store')
    op.drop_column('orders', 'city', schema='clothing_store')
    op.drop_column('orders', 'delivery_address', schema='clothing_store')
    op.drop_column('orders', 'phone', schema='clothing_store')
    op.drop_column('orders', 'customer_name', schema='clothing_store')
    # ### end Alembic commands ###
