"""Add product_type and occasion to Product

Revision ID: d71903008a2c
Revises: a2389e42f3b3
Create Date: 2026-08-10 21:53:02.158965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71903008a2c'
down_revision: Union[str, Sequence[str], None] = 'a2389e42f3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(length=60), server_default='unknown', nullable=False), schema='clothing_store')
    op.add_column('products', sa.Column('occasion', sa.String(length=60), nullable=True), schema='clothing_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'occasion', schema='clothing_store')
    op.drop_column('products', 'product_type', schema='clothing_store')
    # ### end Alembic commands ###
